title: Jaeyong Lee
logo: /assets/profile.png
description: |
  Data scientist that makes your life comfortable.  
  [GitHub](https://github.com/jaeyonggy)  
  [LinkedIn](https://www.linkedin.com/in/jaeyonglee5)  
show_downloads: false
theme: jekyll-theme-minimal
